esphome:
  name: bedroom-fan
  friendly_name: bedroom fan

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "30Ik7twrfmrZUV5JyXwhmXxM6kAZcuUykYgekBpVIF4="

ota:
  password: "3f684931c42f5a81cce720eeef59fe59"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.123
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Fan Fallback Hotspot"
    password: "wwZA4xrZLcc5"

fan:
  - platform: speed
    id: bedroom_fan
    output: custom_fan
    name: "Bedroom fan"
    speed_count: 2   
    on_turn_off:
      - switch.turn_off:
          id: low
      - switch.turn_off:
          id: high    



output:
  - platform: template
    id: custom_fan
    type: float
    

    write_action:
      - if:
          condition:
            lambda: 'return (id(bedroom_fan).speed == 1);'
          then:    
                     - switch.turn_on: low
                     - switch.turn_off: high

      - if:
          condition:
            lambda: 'return (id(bedroom_fan).speed == 2);' 
          then:
            # action for speed 1
            - switch.turn_on: high
            
            - switch.turn_off: low

captive_portal:
switch:    
 - platform: gpio  
   name: Fan Low
   id: low
   pin: D1
   internal: true

 - platform: gpio  
   id: high
   name: Fan High
   pin: D2 
   internal: true