esphome:
  name: flow-meter-softener

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "AwId8vq8Y9TCW8z9/mon6R/BkkgD2giKL/hxEtO6GqY="

ota:
  password: "72d009d0d7b62770fe9c520b459a27e3"
globals:
  - id: dim
    type: float
    restore_value: no
    initial_value: '0.99'
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flow-Meter-Softener"
    password: "1UWeaRh9jRe9"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: Flow Meter WiFi
    update_interval: 60s    
   

  - platform: pulse_meter
    pin: 
      number: D6
    name: "water flow"
    unit_of_measurement: "G/min"
    #update_interval: 10s    
    accuracy_decimals: 3
    filters:
      - lambda: return .26 * (x / 360);
      
    total:
      name: "Total water consumption"
      unit_of_measurement: "Gallons"
      device_class: water
      state_class: total_increasing
      accuracy_decimals: 3
     
      filters:
        - lambda: return .26 * (x / 360);

  
    
binary_sensor:
  - platform: gpio
    pin: 
      number: D7
    id: laundry_motion  
    device_class: motion    
    name: "Laundry Storage"    
    filters:
      - delayed_off: 10s
    on_press:
      light.turn_on:
        brightness: 100%
        #transition_length: 2s
        id: Laundry

    on_release:
      then:
        - light.turn_off:
            id: Laundry
            #transition_length: 2s

        
 

text_sensor:
  - platform: version
    name: ESPHome Version

switch:
  - platform: restart
    name: Flow Meter Restart    

 
   
    
         
        

light:
  - platform: monochromatic
    name: "Laundry"
    output:  laundry
    id: Laundry
    #default_transition_length: 2s

output:
  - platform: esp8266_pwm
    id: laundry
    pin: 
      number: D2
    
